### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [Homini57/CPP202309#1]
### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week7/hamming_dist_func
    - Error: cannot pass non-trivial object of type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') to variadic function; expected type from format string was 'char *' [line 21]
        - printf는 C에서 사용되는 출력 함수입니다. c++에서 사용하는 string 객체는 C에서 사용하는 문자열 배열과는 다른 형태이기 때문에 %s 형태를 사용할 수 없습니다.
        - 출력을 위한 함수를 cout 으로 변경해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week2/candy
- Insufficient comments in challenge/week2/temperature
- Insufficient comments in challenge/week2/temperature2
- Insufficient comments in challenge/week7/hamming_dist_func
- Insufficient comments in practice/week7/hamming_dist

**Comment by Homini57** [comment]
이슈 : #1
이슈 해결 commit : a10615f
hamming_dist_func.cpp : 요구 기능이 실행되도록 코드 수정, 주석 추가
기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
candy, temperature, temperature2, hamming_dist 파일에 주석 추가
